from __future__ import annotations

from typing import Callable

from app.storage.runtime import DatabaseConnection, database_connection


MigrationHandler = Callable[[DatabaseConnection], None]


def _id_column_sql(conn: DatabaseConnection) -> str:
    if conn.backend == "postgres":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _column_exists(conn: DatabaseConnection, table_name: str, column_name: str) -> bool:
    if conn.backend == "postgres":
        row = conn.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ? AND column_name = ?
            """,
            (table_name, column_name),
        ).fetchone()
        return row is not None

    columns = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    return any(row[1] == column_name for row in columns)


def _ensure_migration_table(conn: DatabaseConnection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def _applied_versions(conn: DatabaseConnection) -> set[int]:
    _ensure_migration_table(conn)
    rows = conn.execute("SELECT version FROM schema_migrations").fetchall()
    return {int(row[0] if isinstance(row, tuple) else row["version"]) for row in rows}


def _record_migration(conn: DatabaseConnection, version: int, name: str) -> None:
    conn.execute(
        "INSERT INTO schema_migrations (version, name) VALUES (?, ?)",
        (version, name),
    )


def _migration_001_core_schema(conn: DatabaseConnection) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS analyses (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL DEFAULT 'legacy',
            created_at TEXT NOT NULL,
            chain TEXT NOT NULL DEFAULT 'ethereum',
            address TEXT NOT NULL,
            txn_24h INTEGER NOT NULL,
            volume_24h_usd REAL NOT NULL,
            sanctions_exposure_pct REAL NOT NULL,
            mixer_exposure_pct REAL NOT NULL,
            bridge_hops INTEGER NOT NULL,
            score INTEGER NOT NULL,
            risk_level TEXT NOT NULL,
            explanation TEXT NOT NULL
        )
        """
    )
    if not _column_exists(conn, "analyses", "tenant_id"):
        conn.execute("ALTER TABLE analyses ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'legacy'")
    if not _column_exists(conn, "analyses", "chain"):
        conn.execute("ALTER TABLE analyses ADD COLUMN chain TEXT NOT NULL DEFAULT 'ethereum'")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_analyses_tenant_created ON analyses(tenant_id, created_at)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS users (
            id {_id_column_sql(conn)},
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            tenant_id TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'admin',
            created_at TEXT NOT NULL
        )
        """
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            actor_email TEXT NOT NULL,
            action TEXT NOT NULL,
            target TEXT NOT NULL,
            details TEXT NOT NULL
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_tenant_created ON audit_logs(tenant_id, created_at)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS invites (
            id {_id_column_sql(conn)},
            token TEXT NOT NULL UNIQUE,
            email TEXT NOT NULL,
            tenant_id TEXT NOT NULL,
            role TEXT NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            used_at TEXT,
            revoked_at TEXT
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_invites_tenant_email ON invites(tenant_id, email)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS watchlist (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL,
            chain TEXT NOT NULL,
            address TEXT NOT NULL,
            label TEXT NOT NULL,
            created_at TEXT NOT NULL,
            created_by TEXT NOT NULL,
            last_seen_at TEXT,
            last_score INTEGER,
            alert_on_activity INTEGER NOT NULL DEFAULT 1,
            UNIQUE(tenant_id, chain, address)
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_watchlist_tenant ON watchlist(tenant_id)"
    )


def _migration_002_alerts_and_incidents(conn: DatabaseConnection) -> None:
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS alert_events (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            trigger TEXT NOT NULL,
            chain TEXT NOT NULL,
            address TEXT NOT NULL,
            score INTEGER NOT NULL,
            risk_level TEXT NOT NULL,
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            acknowledged INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_alert_events_tenant ON alert_events(tenant_id, created_at)"
    )

    for column_name, ddl in [
        ("alert_type", "TEXT NOT NULL DEFAULT 'score_threshold'"),
        ("severity", "TEXT NOT NULL DEFAULT 'warning'"),
        ("prev_score", "INTEGER"),
        ("acknowledged_at", "TEXT"),
        ("resolved_at", "TEXT"),
        ("incident_id", "INTEGER"),
    ]:
        if not _column_exists(conn, "alert_events", column_name):
            conn.execute(f"ALTER TABLE alert_events ADD COLUMN {column_name} {ddl}")

    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_alert_events_severity ON alert_events(tenant_id, severity, acknowledged)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_alert_events_feed ON alert_events(tenant_id, id)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS incidents (
            id          {_id_column_sql(conn)},
            tenant_id   TEXT NOT NULL,
            title       TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            severity    TEXT NOT NULL DEFAULT 'warning',
            status      TEXT NOT NULL DEFAULT 'open',
            alert_count INTEGER NOT NULL DEFAULT 0,
            created_at  TEXT NOT NULL,
            updated_at  TEXT NOT NULL,
            resolved_at TEXT,
            created_by  TEXT NOT NULL DEFAULT ''
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_incidents_tenant_updated ON incidents(tenant_id, updated_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_incidents_tenant_status ON incidents(tenant_id, status, updated_at)"
    )

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS webhooks (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL,
            url TEXT NOT NULL,
            events TEXT NOT NULL,
            created_at TEXT NOT NULL,
            active INTEGER NOT NULL DEFAULT 1
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_webhooks_tenant ON webhooks(tenant_id)"
    )


def _migration_003_cases_and_analysis_metadata(conn: DatabaseConnection) -> None:
    if not _column_exists(conn, "analyses", "tenant_id"):
        conn.execute("ALTER TABLE analyses ADD COLUMN tenant_id TEXT NOT NULL DEFAULT 'legacy'")
    if not _column_exists(conn, "analyses", "chain"):
        conn.execute("ALTER TABLE analyses ADD COLUMN chain TEXT NOT NULL DEFAULT 'ethereum'")
    if not _column_exists(conn, "analyses", "tags"):
        conn.execute("ALTER TABLE analyses ADD COLUMN tags TEXT NOT NULL DEFAULT ''")

    if not _column_exists(conn, "users", "role"):
        conn.execute("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'admin'")
    if not _column_exists(conn, "invites", "revoked_at"):
        conn.execute("ALTER TABLE invites ADD COLUMN revoked_at TEXT")

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS cases (
            id {_id_column_sql(conn)},
            tenant_id TEXT NOT NULL,
            title TEXT NOT NULL,
            status TEXT NOT NULL,
            priority TEXT NOT NULL,
            summary TEXT NOT NULL,
            owner_email TEXT NOT NULL DEFAULT '',
            source_type TEXT NOT NULL DEFAULT 'manual',
            source_ref TEXT NOT NULL DEFAULT '',
            primary_chain TEXT NOT NULL DEFAULT '',
            primary_address TEXT NOT NULL DEFAULT '',
            risk_score INTEGER NOT NULL DEFAULT 0,
            risk_level TEXT NOT NULL DEFAULT 'low',
            tags TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            closed_at TEXT
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_cases_tenant_updated ON cases(tenant_id, updated_at)")

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS case_events (
            id {_id_column_sql(conn)},
            case_id INTEGER NOT NULL,
            tenant_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            actor_email TEXT NOT NULL,
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_case_events_case_created ON case_events(case_id, created_at)")

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS case_notes (
            id {_id_column_sql(conn)},
            case_id INTEGER NOT NULL,
            tenant_id TEXT NOT NULL,
            note_type TEXT NOT NULL,
            body TEXT NOT NULL,
            tags TEXT NOT NULL DEFAULT '',
            author_email TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_case_notes_case_created ON case_notes(case_id, created_at)")

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS case_entities (
            id {_id_column_sql(conn)},
            case_id INTEGER NOT NULL,
            tenant_id TEXT NOT NULL,
            entity_type TEXT NOT NULL,
            label TEXT NOT NULL,
            chain TEXT NOT NULL DEFAULT '',
            reference TEXT NOT NULL,
            risk_score INTEGER,
            risk_level TEXT,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_case_entities_case_created ON case_entities(case_id, created_at)")

    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS case_attachments (
            id {_id_column_sql(conn)},
            case_id INTEGER NOT NULL,
            tenant_id TEXT NOT NULL,
            file_name TEXT NOT NULL,
            file_url TEXT NOT NULL,
            content_type TEXT NOT NULL,
            uploaded_by TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_case_attachments_case_created ON case_attachments(case_id, created_at)")


MIGRATIONS: tuple[tuple[int, str, MigrationHandler], ...] = (
    (1, "core_schema", _migration_001_core_schema),
    (2, "alerts_incidents_webhooks", _migration_002_alerts_and_incidents),
    (3, "cases_and_analysis_metadata", _migration_003_cases_and_analysis_metadata),
)


def available_migration_versions() -> tuple[int, ...]:
    return tuple(version for version, _, _ in MIGRATIONS)


def apply_migrations(db_path: str | None = None) -> None:
    with database_connection(db_path) as conn:
        _ensure_migration_table(conn)
        applied = _applied_versions(conn)
        for version, name, handler in MIGRATIONS:
            if version in applied:
                continue
            handler(conn)
            _record_migration(conn, version, name)
        conn.commit()


def get_applied_migration_versions(db_path: str | None = None) -> tuple[int, ...]:
    with database_connection(db_path) as conn:
        versions = sorted(_applied_versions(conn))
    return tuple(versions)


def migration_status_summary(db_path: str | None = None) -> dict[str, object]:
    available = available_migration_versions()
    applied = get_applied_migration_versions(db_path)
    pending = tuple(version for version in available if version not in applied)
    return {
        "applied_versions": list(applied),
        "pending_versions": list(pending),
        "current_version": max(applied, default=0),
        "available_version": max(available, default=0),
        "up_to_date": not pending,
    }
